#!/usr/bin/env bash
# Usage: homesync relpath dir target
# Summary: Returns the relative path target target from dir

if [ $# -ne 2 ]; then
  homesync-help relpath
  exit 1
fi

expand_path() {
  if [ -d "$1" ]; then
    pushd "$1" >/dev/null
    pwd
    popd >/dev/null
  elif [ -e "$1" ]; then
    pushd "$(dirname "$1")" >/dev/null
    echo "$(pwd)/$(basename "$1")"
    popd >/dev/null
  elif [[ $1 = /* ]]; then
    echo $1
  else
    echo "$(pwd)/$1"
  fi
}

dir="$1"
dir="${dir//\/\//\/}"
dir="${dir%/}"
target="$(expand_path "$2")"
target="${target//\/\//\/}"
target="${target%/}"

IFS=/
dirs=(${dir#/})

commonPrefix=/
for d in "${dirs[@]}"; do
  case "$target/" in
    "$commonPrefix$d/"* )
      ;;
    * )
      break
      ;;
  esac
  commonPrefix+="$d/"
done
ancestor="${dir#${commonPrefix%/}}"
ancestor=${ancestor//[^\/]/}
ancestor=${ancestor//\//..\/}
echo "$ancestor${target#$commonPrefix}"
