#!/usr/bin/env bash
# Usage: homesync app AppName
# Summary: Sets up syncing preferences and application data of AppName
# Summary: Sets up syncing preferences and application data of AppName.
#
# Homesync tries to find the preference file and Application Support directory
# for AppName using a set of rules. The recognized paths will be passed on to
# the sync command one by one.

set -e

AppName=$1

paths=$(homesync-app-paths $AppName)

IFS=$'\n'
for path in $paths; do
  homesync-sync "$path"
done
